spring:
  application:
    name: masker

masker:
  source-dir: '/home/nikolay/coding/sber/temp/arch'
  target-dir: '/home/nikolay/coding/sber/temp/to'
  dictionary:
    - replace: 'sber'
      to: 'test'
    - replace: 'Сбер'
      to: 'ООО Тест'
    - replace: 'ЕФС'
      to: 'NNNNNN'
    - replace: 'Предоставлен'
      to: 'Новоеслово'
    - replace: 'Архитектурн'
      to: 'aaaaaaaaaaaaaa'

