spring:
  application:
    name: masker

masker:
  source-dir: '/home/nikolay/coding/sber/temp/KA_DZO'
  target-dir: '/home/nikolay/coding/sber/temp/target-dir'
  dictionary:
    - replace: 'sber'
      to: 'test'
    - replace: 'Сбер'
      to: 'ООО Тест'
    - replace: 'ЕФС'
      to: 'NNNNNN'

