spring:
  application:
    name: masker

masker:
  source-dir: '/home/nikolay/coding/sber/temp/KA_DZO'
  target-dir: '/home/nikolay/coding/sber/temp/target-dir'
  dictionary:
    company-name: 'OOO Test'
    company-prefix: 'test'
